### ISSUE TITLE
Gahoot does not work over SSL

### ISSUE THREAD

**Issue by KekoaM** [ejv2/gahoot#2]
Mobile browsers cannot connect to Gahoot games due to websocket security mismatches.

Steps to reproduce:

1. Run Gahoot behind a reverse proxy providing SSL termination
2. Connect to Gahoot on a mobile browser using https
3. Join a Gahoot game

Attempted fixes:
- Changing the client side js use only `wss` for secure websockets
  - This fix only works for Gahoot servers that use SSL, causing http-only sessions to break

**Comment by ejv2** [comment]
Thanks for the report! I had no idea this was a problem (shows how much I know about mobile). I think the best way of doing this would be to add a configuration variable which tells Gahoot if SSL is to be used. If so, pass something to the client which mirrors the SSL flag and enables ``wss``. That way, we get to preserve HTTP sessions which are already in use.

**Comment by ejv2** [comment]
I've written something similar to what I posted last week. Please pull the latest from the ssl branch and see if it fixes your issue.
